version: '3.8'

services:
  my-onsen-book-db:
    image: mysql:8.0
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    container_name: my-onsen-book-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: my_onsen_book_development
      MYSQL_PASSWORD: password
    ports:
      - 4306:3306
    volumes:
      - mysql-db:/var/lib/mysql
    networks:
      - my_onsen_book_network

  my-onsen-book-rails:
    tty: true
    depends_on:
      - my-onsen-book-db
    image: my-onsen-book-rails
    container_name: my-onsen-book-rails
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/my-onsen-book-rails
    command: bash -c "bundle install && rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    networks:
      - my_onsen_book_network

volumes:
  mysql-db:
    driver: local
networks:
  my_onsen_book_network:
    external: true
