- id: 1
  str_key: "hokkaido"
  name: "北海道"
- id: 2
  str_key: "aomori"
  name: "青森県"
- id: 3
  str_key: "iwate"
  name: "岩手県"
- id: 4
  str_key: "miyagi"
  name: "宮城県"
- id: 5
  str_key: "akita"
  name: "秋田県"
- id: 6
  str_key: "yamagata"
  name: "山形県"
- id: 7
  str_key: "fukushima"
  name: "福島県"
- id: 8
  str_key: "ibaraki"
  name: "茨城県"
- id: 9
  str_key: "tochigi"
  name: "栃木県"
- id: 10
  str_key: "gunma"
  name: "群馬県"
- id: 11
  str_key: "saitama"
  name: "埼玉県"
- id: 12
  str_key: "chiba"
  name: "千葉県"
- id: 13
  str_key: "tokyo"
  name: "東京都"
- id: 14
  str_key: "kanagawa"
  name: "神奈川県"
- id: 15
  str_key: "niigata"
  name: "新潟県"
- id: 16
  str_key: "toyama"
  name: "富山県"
- id: 17
  str_key: "ishikawa"
  name: "石川県"
- id: 18
  str_key: "fukui"
  name: "福井県"
- id: 19
  str_key: "yamanashi"
  name: "山梨県"
- id: 20
  str_key: "nagano"
  name: "長野県"
- id: 21
  str_key: "gifu"
  name: "岐阜県"
- id: 22
  str_key: "shizuoka"
  name: "静岡県"
- id: 23
  str_key: "aichi"
  name: "愛知県"
- id: 24
  str_key: "mie"
  name: "三重県"
- id: 25
  str_key: "shiga"
  name: "滋賀県"
- id: 26
  str_key: "kyoto"
  name: "京都府"
- id: 27
  str_key: "osaka"
  name: "大阪府"
- id: 28
  str_key: "hyogo"
  name: "兵庫県"
- id: 29
  str_key: "nara"
  name: "奈良県"
- id: 30
  str_key: "wakayama"
  name: "和歌山県"
- id: 31
  str_key: "tottori"
  name: "鳥取県"
- id: 32
  str_key: "shimane"
  name: "島根県"
- id: 33
  str_key: "okayama"
  name: "岡山県"
- id: 34
  str_key: "hiroshima"
  name: "広島県"
- id: 35
  str_key: "yamaguchi"
  name: "山口県"
- id: 36
  str_key: "tokushima"
  name: "徳島県"
- id: 37
  str_key: "kagawa"
  name: "香川県"
- id: 38
  str_key: "ehime"
  name: "愛媛県"
- id: 39
  str_key: "kochi"
  name: "高知県"
- id: 40
  str_key: "fukuoka"
  name: "福岡県"
- id: 41
  str_key: "saga"
  name: "佐賀県"
- id: 42
  str_key: "nagasaki"
  name: "長崎県"
- id: 43
  str_key: "kumamoto"
  name: "熊本県"
- id: 44
  str_key: "oita"
  name: "大分県"
- id: 45
  str_key: "miyazaki"
  name: "宮崎県"
- id: 46
  str_key: "kagoshima"
  name: "鹿児島県"
- id: 47
  str_key: "okinawa"
  name: "沖縄県"
